### Dylan Renard
### Applied Machine Learning JHU
### Homework 1
### Professor Alhassan
### Feb 1st, 2026


## HW Assignment 2: Applied Machine Learning @JHU

In [1]:
# %pip install pandas
import pandas as pd

#### Q1 [20 pts] At a high level (i.e., without entering into mathematical details), please describe, compare, and contrast the following classifiers:

* Perceptron (textbook's version)
* SVM 
* Decision Tree
* Random Forrest (you have to research a bit about this classifier)

##### Some Comparison criteria can be:
* Speed?
* Strength?
* Robustness?
* The feature type that the classifier naturally uses (e.g. Relying on distance means that numerical features are naturally used)
* Is it statistical?
* Does the method solve an optimization problem? If yes, what is the cost function?
Which one will be the first that you would try on a dataset?


##### Perceptron
The Perceptron is one of the earliest and simplest linear classifiers and is commonly introduced as a foundational learning algorithm. It learns a linear decision boundary by iteratively updating its weights when a data point is misclassified. The Perceptron is very fast to train and works naturally with numerical features, but it can only learn linearly separable patterns and is sensitive to noise and outliers. While it is not explicitly a statistical model, it can be viewed as performing an implicit form of optimization through mistake-driven weight updates (Raschka et al., 2022).

##### Support Vector Machine (SVM)
Support Vector Machines are margin-based classifiers that aim to find a decision boundary that maximizes the separation between classes. By maximizing this margin, SVMs tend to generalize well and are more robust to noise compared to simpler linear models. SVMs rely on distance-based computations and therefore naturally operate on numerical features. They explicitly solve a convex optimization problem, and through the use of kernel functions, they can model non-linear decision boundaries, though this increases computational cost (Raschka et al., 2022).

##### Decision Tree
A Decision Tree is a rule-based, non-linear classifier that recursively partitions the feature space into regions based on feature values. Decision Trees are relatively fast to train, highly interpretable, and can naturally handle both numerical and categorical features without requiring feature scaling. Rather than solving a single global optimization problem, Decision Trees use greedy, locally optimal splitting criteria to reduce impurity at each node. A major limitation of Decision Trees is their tendency to overfit, particularly when the tree grows deep (Raschka et al., 2022).

##### Random Forest
A Random Forest is an ensemble learning method that constructs many decision trees using bootstrapped samples of the data and random subsets of features, and then aggregates their predictions. This ensemble strategy reduces variance and improves robustness by averaging across many diverse trees compared to a single Decision Tree. Random Forests can model complex, non-linear relationships and handle mixed feature types effectively, though they are typically slower to train than individual trees. Random Forests have demonstrated strong performance in real-world applications, including clinical prediction tasks such as COVID-19 survival analysis, highlighting their robustness on complex datasets (Yazdani et al., 2024).

##### Which classifier would I try first and why?

Each of the classifiers discussed has advantages and limitations depending on the dataset and modeling goals. The Perceptron is extremely fast and simple, but its restriction to linear decision boundaries makes it a weak choice for complex or noisy datasets. Support Vector Machines offer strong generalization through margin maximization, but they rely heavily on numerical, well-scaled features and can become computationally expensive as dataset size grows. Decision Trees are interpretable and naturally handle mixed feature types, but a single tree is prone to overfitting and can be unstable with small changes in the data.

Given these trade-offs, I would first try a Random Forest. By aggregating many decision trees trained on different subsets of the data and features, Random Forests reduce variance and improve robustness compared to individual models. They handle non-linear relationships and mixed feature types well, require relatively little preprocessing, and often provide strong baseline performance without extensive tuning. As a result, Random Forests offer a practical balance between model strength, robustness, and ease of use when exploring a new dataset.

#### Q2 [20 pts] Define the following feature types and give example values from a dataset. 
#### You can pull examples from an existing dataset (like the Iris dataset) or you could write out a dataset yourself. (Hint: In order to give examples for each feature type, you will probably have to use more than one dataset.) 

##### Using the Toy Dataset example from the game Pokemon FireRed which I'm currently emulating on my Android tablet.

* Numerical - Numerical features take continuous or discrete numeric values and support mathematical operations. For example my growlithe level = 34. 

* Nominal - Nominal features take values from a finite set with no inherent ordering. For example growlithe's pokemon_type = "Fire".

* Date - Date features represent calendar-based time information. For example Growlithe's capture_date = "2026-01-03".

* Text - Text features consist of free-form strings that may require additional processing. For example Growlithe's Pokedex_Description = "Very friendly and faithful to people. It will try to repel enemies by barking and biting" (Masuda, 2004).

* Image - image features are represented as pixel intensity values across one or more channels. For example, a 96x96 RGB sprite of Growlithe 

![growlith image](growlithe.png) 
  *Figure 1. Growlithe sprite from Pokémon FireRed (Masuda, 2004).*

* Dependent variable - The dependent variable is the target that a machine learning model aims to predict. For example, In a battle scenario, the dependent variable could be the move selected by an opposing Pokémon, such as predicting which move Grimer will use from {Sludge, Minimize, Disable, Harden}.

#### Q3 [20 pts] Using online resources, research and find other classifier performance metrics which are also as common as the accuracy metric. Provide the mathematical equations for them and explain in your own words the meaning of the different metrics you found.

#### Note that providing mathematical equations might involve defining some more fundamentalterms, e.g. you should define “False Positive,” if you answer with a metric that builds on that.

Accuracy is one of the most commonly reported classifier performance metrics, but its limitations have been increasingly highlighted in recent methodological research. In exploring this topic, a recent 2025 article I found through the Johns Hopkins Catalyst database caught my attention: *What is “accuracy”? Rethinking machine learning classifier performance metrics for highly imbalanced, high variance, zero-inflated species count data*, published in *Limnology and Oceanography: Methods*. This work, conducted by researchers affiliated with the Centre for Sustainable Aquatic Ecosystems and related institutes at Murdoch University in Australia, examines classifier evaluation in the context of ecological datasets where class imbalance and rarity are common. Their analysis demonstrates that accuracy alone can provide a misleading assessment of model performance, motivating the use of additional metrics such as precision, recall, and F1-score to better capture different types of classification errors (Owen et al., 2025). Their case study analysis motivates the use of the following performance metrics/formulas.

To define these metrics, we first introduce the **confusion matrix** terms for a binary classifier:

- **True Positive (TP):** The model correctly predicts the positive class.
- **False Positive (FP):** The model incorrectly predicts the positive class.
- **True Negative (TN):** The model correctly predicts the negative class.
- **False Negative (FN):** The model incorrectly predicts the negative class.

### Accuracy
Accuracy measures the proportion of correct predictions over all predictions.

$$
\text{Accuracy} = \frac{TP + TN}{TP + TN + FP + FN}
$$

Accuracy provides a high-level measure of correctness, but it can be inflated in datasets where one class dominates. As discussed in the context of imbalanced ecological datasets, high accuracy does not necessarily indicate good model performance on rare classes of interest (Owen et al., 2025).


### Precision
Precision measures how many of the instances predicted as positive are actually positive.

$$
\text{Precision} = \frac{TP}{TP + FP}
$$

Precision is particularly informative when false positives are costly, as it reflects how reliable positive predictions are. In imbalanced settings, precision helps reveal whether a classifier is over-predicting the positive class.


### Recall (Sensitivity)
Recall measures how many actual positive instances are correctly identified by the model.

$$
\text{Recall} = \frac{TP}{TP + FN}
$$

Recall is critical when missing positive cases is costly, such as when detecting rare events. In datasets with class imbalance or zero inflation, recall often provides a more meaningful measure of performance than accuracy alone (Owen et al., 2025).


### F1-Score
The F1-score is the harmonic mean of precision and recall.

$$
\text{F1-score} = \frac{2 \cdot (\text{Precision} \cdot \text{Recall})}{\text{Precision} + \text{Recall}}
$$

The F1-score balances the trade-off between false positives and false negatives, making it especially useful for evaluating classifiers on imbalanced datasets. As highlighted in recent evaluations of classifier performance, metrics such as the F1-score provide a more informative summary of performance than accuracy in these settings (Owen et al., 2025).


### Summary
Accuracy, precision, recall, and F1-score are among the most commonly used classifier performance metrics. While accuracy offers a simple overall measure, it can obscure poor performance on minority classes. Metrics such as precision, recall, and F1-score provide a more nuanced and reliable assessment of classifier behavior, particularly for imbalanced and high-variance datasets.

#### Q4 [40 pts] Implement a correlation program from scratch to look at the correlations between the features of Admission_Predict.csv dataset file. (This Graduate Admission dataset, with 9 features and 500 data points, is not provided on Canvas; you have to download it from Kaggle by following the instructions in the module Jupyter notebook.) Remember, you are not allowed to used numpy functions such as mean(), stdev(), cov(), etc. You may use DataFrame.corr() only to verify the correctness of your from-scratch matrix.

In [2]:
# Load dataset
df = pd.read_csv("Admission_Predict_Ver1.1.csv")

# Remove leading/trailing whitespace from column names
# (some columns in the dataset contain trailing spaces)
df.columns = df.columns.str.strip()

# Inspect column names to verify cleanup
print(list(df.columns))

# Separate features from non-feature columns:
# - 'Serial No.' is an identifier and carries no predictive meaning
# - 'Chance of Admit' is the dependent variable (target) and is excluded
#   to avoid target leakage during feature correlation analysis
#
# NOTE: If you wish to explore correlations across all columns (including
# the target or identifier) for exploratory purposes, you may comment out
# the line below.
features = df.drop(columns=["Serial No.", "Chance of Admit"])

print("Feature matrix shape:", features.shape)
print("Feature columns:", list(features.columns))

['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA', 'Research', 'Chance of Admit']
Feature matrix shape: (500, 7)
Feature columns: ['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA', 'Research']

In [3]:
# From-scratch statistical helper functions
#
# These functions implement the components required to compute
# Pearson correlation without using NumPy statistical utilities.
# Writing them explicitly illustrates how correlation is built
# from centering, scaling, and joint variation of features.

def mean(x):
    """Compute the arithmetic mean of a 1D list of values."""
    return sum(x) / len(x)


def std(x):
    """Compute the population standard deviation of a 1D list."""
    mu = mean(x)
    return (sum((xi - mu) ** 2 for xi in x) / len(x)) ** 0.5


def covariance(x, y):
    """Compute the population covariance between two feature vectors."""
    mx, my = mean(x), mean(y)
    return sum((xi - mx) * (yi - my) for xi, yi in zip(x, y)) / len(x)


def pearson_corr(x, y):
    """Compute the Pearson correlation coefficient between two features."""
    sx, sy = std(x), std(y)
    if sx == 0 or sy == 0:
        return 0.0
    return covariance(x, y) / (sx * sy)


# Method: compute Pearson correlation matrix from scratch
def compute_correlation_matrix(df):
    """Compute a feature-by-feature Pearson correlation matrix."""
    cols = list(df.columns)
    corr_matrix = pd.DataFrame(index=cols, columns=cols, dtype=float)

    for c1 in cols:
        x = df[c1].tolist()
        for c2 in cols:
            y = df[c2].tolist()
            corr_matrix.loc[c1, c2] = pearson_corr(x, y)

    return corr_matrix

In [4]:
# Run the from-scratch correlation matrix method
corr_scratch = compute_correlation_matrix(features)
corr_scratch

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
GRE Score,1.000000,0.827200,0.635376,0.613498,0.524679,0.825878,0.563398
TOEFL Score,0.827200,1.000000,0.649799,0.644410,0.541563,0.810574,0.467012
University Rating,0.635376,0.649799,1.000000,0.728024,0.608651,0.705254,0.427047
SOP,0.613498,0.644410,0.728024,1.000000,0.663707,0.712154,0.408116
LOR,0.524679,0.541563,0.608651,0.663707,1.000000,0.637469,0.372526
CGPA,0.825878,0.810574,0.705254,0.712154,0.637469,1.000000,0.501311
Research,0.563398,0.467012,0.427047,0.408116,0.372526,0.501311,1.000000

In [5]:
# Validation (Pandas built-in correlation — verification only)
corr_pandas = features.corr()
corr_pandas

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
GRE Score,1.000000,0.827200,0.635376,0.613498,0.524679,0.825878,0.563398
TOEFL Score,0.827200,1.000000,0.649799,0.644410,0.541563,0.810574,0.467012
University Rating,0.635376,0.649799,1.000000,0.728024,0.608651,0.705254,0.427047
SOP,0.613498,0.644410,0.728024,1.000000,0.663707,0.712154,0.408116
LOR,0.524679,0.541563,0.608651,0.663707,1.000000,0.637469,0.372526
CGPA,0.825878,0.810574,0.705254,0.712154,0.637469,1.000000,0.501311
Research,0.563398,0.467012,0.427047,0.408116,0.372526,0.501311,1.000000

In [6]:
# Quantitative validation: maximum absolute difference
max_abs_diff = (corr_scratch - corr_pandas).abs().to_numpy().max()
print(max_abs_diff, type(max_abs_diff), " Dang that is a small error sheeeeeeesh! :-O")

1.2212453270876722e-15 <class 'numpy.float64'>  Dang that is a small error sheeeeeeesh! :-O

##### Q4 Reflection
The correlation matrix reveals strong positive relationships among quantitative academic metrics, most notably between GRE Score and TOEFL Score (r ≈ 0.83), GRE Score and CGPA (r ≈ 0.83), and TOEFL Score and CGPA (r ≈ 0.81), indicating substantial co-variation among standardized testing and academic performance measures. In contrast, Research experience shows more moderate correlations with other features (r ≈ 0.37–0.56), suggesting it captures a more independent dimension of an applicant’s profile compared to test scores and GPA.

When validating the from-scratch Pearson correlation implementation against features.corr(), the maximum absolute difference observed was on the order of numerical precision (≈10⁻¹²), confirming that the custom implementation is mathematically consistent with the library-based computation and that any discrepancies are attributable to floating-point rounding rather than algorithmic error.

#### References:

Datta, N. (2020, October 25). 📖 graduate admission chances 📕 📔. Kaggle. https://www.kaggle.com/code/nitindatta/graduate-admission-chances/input 

Masuda, J. (2004, January 29) Pokemon FireRed (GBA Version) [Video game]. Game Freak.


Owen, B. M., Tweedley, J. R., Moheimani, N. R., Hallett, C. S., Cosgrove, J. J., & Silberstein, L. P. O. (2025). What is “accuracy”? Rethinking machine learning classifier performance metrics for highly imbalanced, high variance, zero-inflated species count data. Limnology and Oceanography, Methods. https://doi.org/10.1002/lom3.70009


Raschka, S., Liu, Y., & Mirjalili, V. (2022). Machine learning with pytorch and scikit-learn : develop machine learning and deep learning models with python. Packt Publishing.

Yazdani, A., Erfannia, L., Farzaneh, A., & Ali, O. (2024). Survival Analysis of Patients with COVID-19 using Deep Neural Network and Random Forrest Techniques. Frontiers in Health Informatics, 13, 186. https://doi.org/10.30699/fhi.v13i0.512